# Format : UUID  MAPPER_NAME  MOUNT_POINT
# Lignes vides et commentaires (#) ignorés

# xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  macleusb    /mnt/macleusb
# yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy  cle-backup  /mnt/backup
# zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz  cle-cours   /mnt/cours
