# ~/.config/starship/default.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 3000

# Votre configuration personnelle détaillée
# Par exemple, avec des icônes, des couleurs subtiles, etc.
[username]
show_always = true
style_user = "blue bold"
format = '[$user]($style) '

[directory]
style = "cyan"
format = '󰝰 [$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = "🌱 "

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

[hostname]
ssh_only = false
format = '󰌢 [$hostname](bold red) '
disabled = false